# Generated by Django 4.0.5 on 2022-06-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsonzambia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.TextField(default=None)),
            ],
        ),
    ]
